pipeline:
  identifier: Build_srikanthlahanday_simple_java_maven_app_1736258370734
  name: Build simple-java-maven-app
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1736242057608
        repoName: srikanthlahanday/simple-java-maven-app
  stages:
    - stage:
        identifier: build
        name: build test and publish
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: casestudy1
                    build:
                      type: branch
                      spec:
                        branch: master
              - step:
                  type: RunTests
                  name: Build Java Code
                  identifier: Build_Java_Code
                  spec:
                    language: Java
                    buildTool: Maven
                    args: mvn clean install -DskipTests
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths: <+input>
                    enableTestSplitting: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          buildIntelligence:
            enabled: false
        type: CI
        description: ""
