pipeline:
  identifier: Build_srikanthlahanday_simple_java_maven_app_1736258370734
  name: Build simple-java-maven-app
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1736242057608
        repoName: srikanthlahanday/simple-java-maven-app
  stages:
    - stage:
        identifier: build
        name: build test and publish
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: casestudy1
                    cloneDirectory: /harness/simple-java-maven-app
                    build:
                      type: branch
                      spec:
                        branch: master
              - step:
                  type: Run
                  name: Maven
                  identifier: Maven
                  spec:
                    shell: Sh
                    command: mvn clean install -DskipTests
              - step:
                  type: RunTests
                  name: mvn
                  identifier: RunTests_1
                  spec:
                    language: Java
                    buildTool: Maven
                    args: mvn clean install -DskipTests
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          buildIntelligence:
            enabled: false
        type: CI
        description: ""
